services:
  api_gateway:
    container_name: api_gateway
    build: ./api_gateway
    image: api_gateway
    ports:
      - 49998:80
    restart: unless-stopped
    networks:
      - backend_net

  frontend:
    container_name: frontend
    build: ./frontend
    image: frontend
    ports:
      - 49999:80
    volumes:
      - ./frontend/app:/usr/share/nginx/html
    restart: unless-stopped

  user_management_api:
    container_name: user_management_api
    build: ./user_management
    image: user_management_api
    volumes:
      - ./user_management/app:/usr/src/app
    depends_on:
      - user_management_db
    restart: unless-stopped
    networks:
      - user_management_net
      - backend_net

  user_management_db:
    container_name: user_management_db
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: api-db
    restart: unless-stopped
    networks:
      - user_management_net

  multiplayer_service:
    container_name: multiplayer_service
    build: ./multiplayer
    image: multiplayer_service
    volumes:
      - ./multiplayer/app/multiplayer_service:/usr/src/app
    depends_on:
      - match_history_rabbitmq
    restart: unless-stopped
    networks:
      - backend_net

  chat_service:
    container_name: chat_service
    build: ./chat
    image: chat_service
    depends_on:
      - chat_db
    volumes:
      - ./chat/app/chat_service:/usr/src/app
    restart: unless-stopped
    networks:
      - chat_net
      - backend_net

  chat_db:
    container_name: chat_db
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: chat-db
    restart: unless-stopped
    networks:
      - chat_net

  match_history_api:
    container_name: match_history_api
    build: ./match_history
    image: match_history_api
    volumes:
      - ./match_history/app:/usr/src/app
    depends_on:
      - match_history_db
      - match_history_rabbitmq
    restart: unless-stopped
    networks:
      - match_history_net
      - backend_net

  match_history_db:
    container_name: match_history_db
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: api-db
    restart: unless-stopped
    networks:
      - match_history_net

  match_history_rabbitmq:
    image: rabbitmq:3-management
    container_name: match_history_rabbitmq
    ports:
      - "5672:5672"       # Puerto de comunicación entre servicios
      - "15672:15672"     # Interfaz de administración de RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    restart: unless-stopped
    networks:
      - backend_net

networks:
  user_management_net:
    driver: bridge
  chat_net:
    driver: bridge
  backend_net:
    driver: bridge
  match_history_net:
    driver: bridge
